language: php

php:
  - "7.2"
  - "7.3"
  - "7.4"

before_install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
